"""Updated leave schema

Revision ID: 23424e1f311e
Revises: a14c6252226b
Create Date: 2025-12-20 12:29:58.854828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23424e1f311e'
down_revision = 'a14c6252226b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
