"""Updated leave schema

Revision ID: 32742791d79d
Revises: 23424e1f311e
Create Date: 2025-12-20 12:56:21.731175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32742791d79d'
down_revision = '23424e1f311e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('approved_by',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.alter_column('approved_by',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###
